### ISSUE TITLE
Does not interact with libsodium

### ISSUE THREAD

**Issue by jcking89** [lyubo/react-native-sodium#15]
The sign length is different between libsodium result and react-native-sodium.
react-native-sodium sig length is always 128, while libsodium sig length is sk.length + msg.length
How can I change react-native-sodium sig length?

**Comment by lyubo** [comment]
which function do you have in mind? can you post a code reproducing the issue?

**Comment by lyubo** [comment]
As there is no any movement here, I will close this one.
