### ISSUE TITLE
Publishing on NPM

### ISSUE THREAD

**Issue by stwiname** [lyubo/react-native-sodium#2]
Could we get this published on npm please?

**Comment by lyubo** [comment]
Sorry, no time at the moment. The project is still not in a good shape for npm. Have to write better README, etc.

**Comment by alexindigo** [comment]
NPM welcomes any shape and form. It will make easier for everybody to try it out and the main thing – would make it enormously easier to discover. Currently npm has only one react-native sodium module and it's Android only.

**Comment by lyubo** [comment]
Published to NPM: https://www.npmjs.com/package/react-native-sodium

**Comment by alexindigo** [comment]
Thanks a lot @lyubo and having example project is a great idea!

**Comment by alexindigo** [comment]
Not sure if it's known, but this is the warning I saw when I ran your example app:

![Main Queue Setup](http://ia.gs/3f637a734b64/Image%202019-01-17%20at%208.25.57%20AM.png)

**Comment by alexindigo** [comment]
Looks like this is could be the fix: https://github.com/facebook/react-native/pull/17679/files

**Comment by lyubo** [comment]
The above proposed fix is applied and published to npm

**Comment by alexindigo** [comment]
Thanks a lot.
