### ISSUE TITLE
React native 0.60+

### ISSUE THREAD

**Issue by max-zu** [lyubo/react-native-sodium#23]
Hi. There is a new feature in react-native 0.60+ which is called [autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md). And CocoaPods is used by Default. So Autolinking relies on `.podspec` file. I tried to fork your repo and add a `.podspec` file but I've failed(. When i try to link manually - i catch this error
![image](https://user-images.githubusercontent.com/22217379/64568586-c6150480-d363-11e9-9857-8ba1a58dbb59.png)

**Comment by jrbaudin** [comment]
@max-zu I've opened a PR to address this, can be found here: https://github.com/lyubo/react-native-sodium/pull/24

This podspec works well for my RN > 0.60 project
