### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by max-zu** [lyubo/react-native-sodium#30]
Could you publish the latest version to the npm please ?)
this pr https://github.com/lyubo/react-native-sodium/pull/27 is critical for our project))
Thanks!)

**Comment by lyubo** [comment]
published v0.3.6.

**Comment by tasn** [comment]
Should this ticket be closed since there's been a release?

**Comment by lyubo** [comment]
Yes, I think so. I was waiting for feedback from @max-zu, but anyway it can be closed.

**Comment by max-zu** [comment]
Thanks. Works like a charm
