### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by tasn** [lyubo/react-native-sodium#33]
TypeScript is great and very popular. I think having typescript typings would be a great addition to this library.

**Comment by lyubo** [comment]
There is another PR which includes among other changes a d.ts file but that PR is not tested on iOS and I currently don't have spare time to test it.

**Comment by tasn** [comment]
Maybe only merge the types?

**Comment by lyubo** [comment]
@tasn  I've published  new npm build with latest PRs, including the one with TypeScript type definitions. As I don't have currently a project TS project which uses rn-sodium, can you please test it and close this issue if it's working?

**Comment by tasn** [comment]
Sorry, it's a terribly busy week for me and I haven't gotten around to testing it, though if the typings have been added, that's great!
I'm closing this ticket and will open a new one if I find a problem with the types.

Thanks!

**Comment by tasn** [comment]
The types I've tested seem to work well, thanks a lot!

Also, while technically the same, I'd maybe add a type alias called `base64` and just use it instead of string where appropriate so people know (IDE completion) what is expected.
