### ISSUE TITLE
No crypto_scalarmult!!!

### ISSUE THREAD

**Issue by IamFlowZ** [lyubo/react-native-sodium#38]
Hi!
I'm currently working on putting together a demo app in React native. It relies on shared key cryptography and the crypto_scalarmult function to mix public keys. I see the crypto_scalarmult_base function, however I don't see crypto_scalarmult. This is a hard road block and im on limited time so I'd love to hear about this soon!

**Comment by IamFlowZ** [comment]
+1

**Comment by lyubo** [comment]
Can't you try to add this one by yourself? I'd be glad to merge your PR.

**Comment by IamFlowZ** [comment]
I'm coming from web, not native. If you could maybe write something up for how to go about achieving this I could attempt it.

**Comment by lyubo** [comment]
I'm on my annual vacation right now, no pc around me, so can't help with
your urgent needs.

But generally, you have to fork this repo then 'git clone' it on your pc,
make the aditions you want, test if everything's working as expected, then
commit changes to your (forked) repo, then create a push request, which I
could merge in my repo. Then I'll publish new build in npm.

**Comment by IamFlowZ** [comment]
I don't know what the process looks like converting C -> native -> react native bindings. I'm familiar with how to submit a PR.

**Comment by lyubo** [comment]
You can use scalarmult_base as a guide. Look for all theplaces
scalarmult_base is mentioned, then try to add scalarmult function in a
similar manner.

**Comment by IamFlowZ** [comment]
Hey @lyubo 
I've been making some progress on this with a fork that seems to be going well. 
However the device I'm communicating with is using libsodium 1.0.18. The version you have packaged is 1.0.17 and from what I can decipher in the patch notes, there were internal changes to the scalar_mult function. Could you possibly verify if these changes affect the scalar_mult function, and if so put together a build of libsodium at 1.0.18?

**Comment by lyubo** [comment]
Sure I will, but it will happen next week at my best. Meanwhile, you can
try to build it by yourself. Rename .sig file to match version 1.0.18, then
edit its content with valid SHA signature (take it from libsodium site)
then run 'npm run rebuild'. This will download version 1.0.18 and build it.
See prerequisites needed for a successful build.

**Comment by IamFlowZ** [comment]
That is super helpful, thank you! I was completely stuck trying to figure out how to upgrade the version myself.

**Comment by lundb1tr** [comment]
Hello @lyubo 
I'm curious if there has been any movement towards updating to 1.0.18.  I am in the process of attempting to update and build myself but am running into some issues.  

Your instructions above seem to reference a build process which was changed in the following commit https://github.com/lyubo/react-native-sodium/pull/34/commits/092548ef751f3c0191d83ae3a4d5cdf5e23a6dc3

**Comment by lyubo** [comment]
> Hello @lyubo
> I'm curious if there has been any movement towards updating to 1.0.18. I am in the process of attempting to update and build myself but am running into some issues.
> 
> Your instructions above seem to reference a build process which was changed in the following commit [092548e](https://github.com/lyubo/react-native-sodium/commit/092548ef751f3c0191d83ae3a4d5cdf5e23a6dc3)

Sorry, my mistake. Basically the process is the same though, one has to download desired version and calculate new checksum with `shasum -a 512`

I will make the upgrade to 1.0.18, and and then I will push a new release to the npm registry, together with your PR.

**Comment by lyubo** [comment]
Hey, @lundb1tr 
I'm going to close this one as there's a new build with merged PR and updated libsodium version.
