### ISSUE TITLE
Gradle build failded for android

### ISSUE THREAD

**Issue by sandeeprao698** [lyubo/react-native-sodium#41]
Hi, I am very new to react-native and i am facing when I use this lib.
I am getting below error whenever i am running `react-native run-android`.
Version used is
"react-native-sodium": "^0.3.8" 
> More than one file was found with OS independent path 'lib/armeabi-v7a/libsodium.so'. If you are using jniLibs and CMake IMPORTED targets
Please let me know how I can solve this.

**Comment by ryanleesipes** [comment]
I'm seeing the same issue, any ideas as to what a fix is here? pickFirst doesn't seem to be working.

**Comment by ryanleesipes** [comment]
@sandeeprao698 did you ever figure out how to fix this? I have used packagingOptions as detailed here: https://github.com/piruin/opencv-android/issues/1 thinking that may help, but I still get the same error.

**Comment by cjroth** [comment]
Hey guys! I was able to fix this with this patch: https://github.com/glancemoney/react-native-sodium/commit/142e3488d051b13e65b2e9ef4950f6272219e1c1. You can apply it with patch-package if you don't want to fork the repo.

**Comment by lyubo** [comment]
Thanks @cjroth 
Can you make a PR?

**Comment by cjroth** [comment]
@lyubo yeah, happy to! I'm not 100% sure if this is something that affects everyone and should be merged into the actual repo or if it is due to some other libraries we are using, so I'd be cautious before you merge it.

**Comment by max-zu** [comment]
https://github.com/lyubo/react-native-sodium/issues/41#issuecomment-723716207
works for me  (RN 0.64.0)

**Comment by benjaminreid** [comment]
I’m getting this issue on a fresh React Native project too.

```bash
npx react-native init SodmiumTest --template react-native-template-typescript
cd SodmiumTest
yarn add react-native-sodium
cd android
./gradlew clean; ./gradlew assembleDebug
```

Results in...

```bash
> Task :react-native-sodium:mergeDebugNativeLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-sodium:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/armeabi-v7a/libsodium.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
```

Dump from `react-native info`.

```bash
System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 481.55 MB / 16.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.13.0 - /var/folders/94/btf_scw12xbdnqv5dtv2t2hr0000gn/T/yarn--1621521776897-0.29015657479352086/node
    Yarn: 1.22.5 - /var/folders/94/btf_scw12xbdnqv5dtv2t2hr0000gn/T/yarn--1621521776897-0.29015657479352086/yarn
    npm: 6.12.0 - ~/.fnm/current/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 24, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by benjaminreid** [comment]
Threw my example up to a repo too if that helps, https://github.com/benjaminreid/sodium-example.

**Comment by benjaminreid** [comment]
Probably the best explanation of the issue, https://stackoverflow.com/questions/62088079/error-when-building-project-with-ndk-support-after-updating-to-android-studio-4.

**Comment by Brummos** [comment]
also having this issue, applied the patch, not working.

Anything we can still try?

**Comment by max-zu** [comment]
i think issue can be closed 
https://github.com/lyubo/react-native-sodium/pull/43
