### ISSUE TITLE
Get FAILURE in crypto_box_easy IOS

### ISSUE THREAD

**Issue by edenmeshulam** [lyubo/react-native-sodium#50]
Hi, someone can help me to find out why i get catch error 
 **LOG  [Error: FAILURE]**
version  4.0.0

code : 

`const ciphertext = await sodium
      .crypto_box_easy(message, nonce, recipientPublicKey, senderPrivateKey)
      .then(res => {
        console.log(res);
      })
      .catch(err => {
        console.log(err);
      });`

**Comment by tgreco** [comment]
@edenmeshulam how did you end up solving this?
