### ISSUE TITLE
Why doesn't this project reuse an existing binding of Libsodium for Android?

### ISSUE THREAD

**Issue by sdduursma** [lyubo/react-native-sodium#6]
This project implements a JNI for Libsodium in `sodium-jni.c`. Is there any reason this project doesn't reuse any of the bindings of Libsodium available for Android, such as [libsodium-jni](https://github.com/joshjdevl/libsodium-jni)? I would expect that reusing an existing binding would make it easier to extend this project, as one would only have to create a React Native wrapper for the code from the existing binding, without having to extend the JNI.

**Comment by acao** [comment]
it already does do this! There are some abstractions it provides on top, im not familiar with java/android but it seems to handle encoding/etc at an abstraction layer, and some `_easy` methods to make things simpler and provide parity with the ios implementation

**Comment by lyubo** [comment]
The above mentioned binding uses SWIG tool to generate Java JNI bindings. I wanted minimal dependencies and more control over code - ex. special memory cleaning of variables when appropriate.
